"""Product-loop substrate (docs 20-23, weeks P1-P2) — the evidence floor.

The outer loop has no compiler, no test suite, no type checker; the typed
claim ledger and the checks in this package are built to be what ears_lint
is upstream. Everything else in the product loop (P0-P5 stages, gates,
voters) stands on this substrate and ships in later milestones.
"""

from ai_venture_studio.product.claim_lint import ClaimIssue, has_causal_language, lint_ledger
from ai_venture_studio.product.handoff import (
    Handoff,
    HandoffError,
    SeedHypothesis,
    emit_handoff,
    validate_handoff_at_dor,
    write_handoff,
)
from ai_venture_studio.product.injection import InjectionFinding, injection_scan
from ai_venture_studio.product.kill_registry import (
    KillMatch,
    KillRecord,
    KillRegistryError,
    load_kill_registry,
    match_killed,
)
from ai_venture_studio.product.market import (
    GATE_PL1_RUBRIC,
    GatePL1Decision,
    GatePL1Entry,
    gate_pl1_entry,
    record_probe,
)
from ai_venture_studio.product.opportunity import (
    DemandHypothesis,
    GatePL0Result,
    OpportunityCandidate,
    RawSignal,
    SignalCluster,
    cluster_signals,
    gate_pl0,
)
from ai_venture_studio.product.loop_metrics import LoopMetrics, loop_metrics
from ai_venture_studio.product.portfolio import (
    GATE_PL5_RUBRIC,
    CycleReport,
    GatePL5Decision,
    GatePL5Entry,
    KillCriterion,
    KillDecisionError,
    KillEvaluation,
    KillRegistryWriteError,
    OutcomeReadingSummary,
    append_kill_record,
    close_kill_evaluation,
    evaluate_kill_criteria,
    gate_pl5_entry,
)
from ai_venture_studio.product.reconcile import (
    HypothesisVerdict,
    Invalidation,
    falsified_ids,
    propagate_invalidations,
)
from ai_venture_studio.product.prd import (
    GATE_PL2_RUBRIC,
    PRD,
    GatePL2Decision,
    Instrumentation,
    Outcome,
    OutcomeTarget,
    PlanningTask,
    PRDDemandHypothesis,
    PrdIssue,
    prd_lint,
)
from ai_venture_studio.product.sizing import (
    SizingFactor,
    SizingIssue,
    SizingResult,
    TopDownCrosscheck,
    sizing_calc,
)
from ai_venture_studio.product.claims import (
    Claim,
    ProductPolicy,
    ProductPolicyError,
    ledger_class_for,
    load_ledger,
    load_product_policy,
    source_types_for,
)
from ai_venture_studio.product.evidence import (
    Snapshot,
    resolve_snapshot,
    snapshot_differs,
    store_snapshot,
    verify_snapshot,
)
from ai_venture_studio.product.persona_scan import PersonaFinding, synthetic_persona_scan
from ai_venture_studio.product.sources import (
    SignalSource,
    SignalSourceError,
    load_signal_sources,
    source_standing_check,
)
from ai_venture_studio.product.taint import TaintPolicyError, load_taint_classes

__all__ = [
    "GATE_PL1_RUBRIC",
    "GATE_PL2_RUBRIC",
    "GATE_PL5_RUBRIC",
    "CycleReport",
    "GatePL5Decision",
    "GatePL5Entry",
    "HypothesisVerdict",
    "Invalidation",
    "KillCriterion",
    "KillDecisionError",
    "KillEvaluation",
    "KillRegistryWriteError",
    "LoopMetrics",
    "OutcomeReadingSummary",
    "append_kill_record",
    "close_kill_evaluation",
    "evaluate_kill_criteria",
    "falsified_ids",
    "gate_pl5_entry",
    "loop_metrics",
    "propagate_invalidations",
    "PRD",
    "Claim",
    "ClaimIssue",
    "DemandHypothesis",
    "GatePL0Result",
    "GatePL1Decision",
    "GatePL1Entry",
    "GatePL2Decision",
    "Handoff",
    "HandoffError",
    "InjectionFinding",
    "Instrumentation",
    "KillMatch",
    "KillRecord",
    "KillRegistryError",
    "OpportunityCandidate",
    "Outcome",
    "OutcomeTarget",
    "PRDDemandHypothesis",
    "PlanningTask",
    "PrdIssue",
    "RawSignal",
    "SeedHypothesis",
    "SignalCluster",
    "SizingFactor",
    "SizingIssue",
    "SizingResult",
    "TopDownCrosscheck",
    "cluster_signals",
    "emit_handoff",
    "gate_pl0",
    "gate_pl1_entry",
    "has_causal_language",
    "injection_scan",
    "load_kill_registry",
    "match_killed",
    "prd_lint",
    "record_probe",
    "sizing_calc",
    "validate_handoff_at_dor",
    "write_handoff",
    "PersonaFinding",
    "ProductPolicy",
    "ProductPolicyError",
    "SignalSource",
    "SignalSourceError",
    "Snapshot",
    "TaintPolicyError",
    "ledger_class_for",
    "lint_ledger",
    "load_ledger",
    "load_product_policy",
    "load_signal_sources",
    "load_taint_classes",
    "resolve_snapshot",
    "snapshot_differs",
    "source_standing_check",
    "source_types_for",
    "store_snapshot",
    "synthetic_persona_scan",
    "verify_snapshot",
]
