#!/usr/bin/env bash
# Scanner-calibration driver (§19 G7, R-G3).
#
# Runs `avs calibrate` for each language lane against the real
# scanners in the Dockerfile.calibrate image, writing per-defect reports to
# .mas/calibration/<lang>.yaml and a roll-up to calibration-summary.md.
#
# Exit status: non-zero if any lane needs recalibration (a manifest pattern
# missed a defect the scanner actually flagged) OR has a skipped slot (a
# scanner the image was supposed to provide is absent). Green means every
# planted defect was caught by the pattern the manifest claims.
#
# Usage (host): make calibrate            # builds the image and runs this
#        (in-container): scripts/calibrate.sh [lang ...]
set -euo pipefail

LANGS=("${@:-java dotnet}")
# shellcheck disable=SC2206
LANGS=(${LANGS[@]})

SUMMARY="calibration-summary.md"
{
  echo "# Scanner calibration summary"
  echo
  echo "Generated by scripts/calibrate.sh. Per-defect detail (with the actual"
  echo "scanner output for every miss) is in .mas/calibration/<lang>.yaml."
  echo
  echo "| Lane | Catch-rate | Caught | Skipped slots | Needs recalibration |"
  echo "|---|---|---|---|---|"
} > "$SUMMARY"

overall_rc=0
for lang in "${LANGS[@]}"; do
  echo "== calibrating ${lang} lane =="
  rc=0
  uv run avs calibrate "$lang" || rc=$?
  [ "$rc" -ne 0 ] && overall_rc=1

  report=".mas/calibration/${lang}.yaml"
  if [ -f "$report" ]; then
    # Pull the roll-up fields with the same yaml the tool wrote them with.
    uv run python - "$lang" "$report" >> "$SUMMARY" <<'PY'
import sys, yaml
lang, path = sys.argv[1], sys.argv[2]
r = yaml.safe_load(open(path))
skipped = ", ".join(r.get("skipped_slots") or []) or "-"
misses = [m for m in r.get("misses", [])]
ran = {s["slot"] for s in r.get("slot_outputs", []) if s["status"] in ("clean", "findings")}
needs = any(m["slot"] in ran for m in misses)
print(f"| {lang} | {r['catch_rate']:.0%} | {r['caught']}/{r['total']} | {skipped} | {'YES' if needs else 'no'} |")
PY
  else
    echo "| ${lang} | (no report) | - | - | ERROR |" >> "$SUMMARY"
    overall_rc=1
  fi
done

echo
echo "== summary written to ${SUMMARY} =="
cat "$SUMMARY"
exit "$overall_rc"
